# fly.toml app configuration file generated for loxewyx-app-api on 2024-08-07T16:08:19+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'loxewyx-app-api'
primary_region = 'mad'

[build]

[deploy]
  release_command = "bunx prisma generate"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
