# fly.toml app configuration file generated for loxewyx-app-api-patient-thunder-3965 on 2024-08-06T23:01:04+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'loxewyx-app-api-patient-thunder-3965'
primary_region = 'mad'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
